# Generated by Django 6.0.5 on 2026-07-07 15:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_rename_timezone_organizationsettings_time_zone_and_more'),
        ('terminals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plate_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('truck_type', models.CharField(choices=[('tanker', 'Tanker'), ('flatbed', 'Flatbed'), ('refrigerated', 'Refrigerated'), ('tow_truck', 'Tow Truck'), ('crane_truck', 'Crane Truck'), ('carrier_truck', 'Carrier Truck'), ('dump_truck', 'Dump Truck'), ('mixer_truck', 'Mixer Truck'), ('semi_truck', 'Semi Truck'), ('sprayer', 'Sprayer'), ('container', 'Container Truck'), ('bulk', 'Bulk Carrier'), ('other', 'Other')], default='tanker', max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, help_text='Capacity in litres', null=True)),
                ('current_status', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('arrived', 'Arrived'), ('at_customer', 'At Customer'), ('faulty', 'Faulty'), ('at_terminal', 'At Terminal'), ('parked', 'Parked'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], db_index=True, default='parked', max_length=30)),
                ('rfid_tag_id', models.CharField(blank=True, db_index=True, help_text='RFID tag EPC number attached to this truck', max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['plate_number'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('premium_motor_spirit', 'Premium Motor Spirit (PMS)'), ('automotive_gas_oil', 'Automotive Gas Oil (AGO)'), ('dual_purpose_kerosene', 'Dual Purpose Kerosene (DPK)'), ('household_kerosene', 'Household Kerosene (HHK)'), ('aviation_turbine_kerosene', 'Aviation Turbine Kerosene (ATK/Jet A-1)'), ('low_pour_fuel_oil', 'Low Pour Fuel Oil (LPFO)'), ('heavy_fuel_oil', 'Heavy Fuel Oil (HFO)'), ('liquefied_petroleum_gas', 'Liquefied Petroleum Gas (LPG)'), ('compressed_natural_gas', 'Compressed Natural Gas (CNG)'), ('liquefied_natural_gas', 'Liquefied Natural Gas (LNG)'), ('natural_gas', 'Natural Gas'), ('bitumen_60_70', 'Bitumen 60/70'), ('bitumen_80_100', 'Bitumen 80/100'), ('bitumen_40_50', 'Bitumen 40/50'), ('polymer_modified_bitumen', 'Polymer Modified Bitumen (PMB)'), ('cationic_bitumen_emulsion', 'Cationic Bitumen Emulsion'), ('anionic_bitumen_emulsion', 'Anionic Bitumen Emulsion'), ('cutback_bitumen', 'Cutback Bitumen'), ('crumb_rubber_modified_bitumen', 'Crumb Rubber Modified Bitumen (CRMB)'), ('engine_oil', 'Engine Oil'), ('gear_oil', 'Gear Oil'), ('hydraulic_oil', 'Hydraulic Oil'), ('transmission_fluid', 'Transmission Fluid'), ('grease', 'Grease'), ('base_oil', 'Base Oil'), ('paraffin_wax', 'Paraffin Wax'), ('solvent', 'Industrial Solvent'), ('marine_gas_oil', 'Marine Gas Oil (MGO)'), ('marine_diesel_oil', 'Marine Diesel Oil (MDO)')], max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='litres', help_text='Unit of measurement e.g. litres, tonnes, kg', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='organization.organizations')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='TruckLocation',
            fields=[
                ('truck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location', serialize=False, to='fleet.truck')),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('speed_kmh', models.FloatField(blank=True, null=True)),
                ('bearing', models.FloatField(blank=True, help_text='Direction of travel in degrees 0-360', null=True)),
                ('provider', models.CharField(default='gambus', help_text='GPS provider that supplied this data point', max_length=100)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truck Location',
                'verbose_name_plural': 'Truck Locations',
            },
        ),
        migrations.AddField(
            model_name='truck',
            name='default_product',
            field=models.ForeignKey(blank=True, help_text='Default product this truck carries — overridable per shipment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='fleet.product'),
        ),
        migrations.AddField(
            model_name='truck',
            name='home_terminal',
            field=models.ForeignKey(blank=True, help_text='Primary terminal this truck is based at', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trucks', to='terminals.terminals'),
        ),
        migrations.AddField(
            model_name='truck',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='organization.organizations'),
        ),
        migrations.CreateModel(
            name='TruckStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('arrived', 'Arrived'), ('at_customer', 'At Customer'), ('faulty', 'Faulty'), ('at_terminal', 'At Terminal'), ('parked', 'Parked'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], max_length=30, null=True)),
                ('new_status', models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound'), ('arrived', 'Arrived'), ('at_customer', 'At Customer'), ('faulty', 'Faulty'), ('at_terminal', 'At Terminal'), ('parked', 'Parked'), ('under_maintenance', 'Under Maintenance'), ('decommissioned', 'Decommissioned')], max_length=30)),
                ('trigger_source', models.CharField(choices=[('rfid', 'RFID Gate Event'), ('manual', 'Manual Override'), ('gps', 'GPS Sync'), ('system', 'System')], default='system', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('triggered_by', models.ForeignKey(blank=True, help_text='The user who triggered this change — null if triggered by RFID or GPS', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='truck_status_changes', to=settings.AUTH_USER_MODEL)),
                ('truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='fleet.truck')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route_name', models.CharField(max_length=255)),
                ('destination', models.CharField(help_text='Customer delivery location name or address', max_length=255)),
                ('standard_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expected_tat_hours', models.DecimalField(blank=True, decimal_places=2, help_text='Expected turnaround time in hours', max_digits=6, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='organization.organizations')),
                ('origin_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outbound_routes', to='terminals.terminals')),
            ],
            options={
                'ordering': ['route_name'],
                'unique_together': {('route_name', 'organization')},
            },
        ),
    ]
