# Generated by Django 6.0.5 on 2026-06-03 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("access", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="verificationtokens",
            name="access_veri_token_e895d0_idx",
        ),
        migrations.RemoveIndex(
            model_name="verificationtokens",
            name="access_veri_user_id_7284e4_idx",
        ),
        migrations.RenameField(
            model_name="verificationtokens",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AddField(
            model_name="verificationtokens",
            name="token_hash",
            field=models.CharField(
                db_index=True, default="", max_length=64, unique=True
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtokens",
            index=models.Index(
                fields=["token_hash"], name="access_veri_token_h_29022d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtokens",
            index=models.Index(fields=["user"], name="access_veri_user_id_7ec653_idx"),
        ),
        migrations.AddIndex(
            model_name="verificationtokens",
            index=models.Index(
                fields=["expires_at"], name="access_veri_expires_729848_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="verificationtokens",
            index=models.Index(
                fields=["token_hash", "token_type", "user"],
                name="access_veri_token_h_80b19c_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="verificationtokens",
            name="token",
        ),
    ]
