# Generated by Django 6.0.5 on 2026-06-16 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "access",
            "0002_remove_verificationtokens_access_veri_token_e895d0_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="verificationtokens",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
