# Generated by Django 6.0.5 on 2026-08-03 23:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_alter_verificationtokens_token_type_usersession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='verificationtokens',
            name='token_type',
            field=models.CharField(choices=[('organization_verification', 'Organization Verification'), ('email_verification', 'Email Verification'), ('password_reset', 'Password Reset'), ('two_factor_auth', 'Two Factor Authentication'), ('refresh_token', 'Refresh Token'), ('delivery_confirmation', 'Delivery Confirmation')], max_length=255),
        ),
        migrations.AlterField(
            model_name='verificationtokens',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
