# Generated by Django 6.0.5 on 2026-08-10 14:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_alter_verificationtokens_token_type_and_more'),
        ('organization', '0003_organizationmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationTokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default='', max_length=255, unique=True)),
                ('token_hash', models.CharField(db_index=True, default='', max_length=64, unique=True)),
                ('token_type', models.CharField(choices=[('user_onboarding', 'User Onboarding'), ('email_verification', 'Email Verification'), ('invitation', 'Invitation'), ('password_reset', 'Password Reset'), ('two_factor_auth', 'Two Factor Authentication'), ('refresh_token', 'Refresh Token'), ('delivery_confirmation', 'Delivery Confirmation')], max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False)),
                ('is_revoked', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict, null=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='verificationtokens',
            name='access_veri_token_t_43af50_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationtokens',
            name='access_veri_token_h_29022d_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationtokens',
            name='access_veri_user_id_7ec653_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationtokens',
            name='access_veri_expires_729848_idx',
        ),
        migrations.RemoveIndex(
            model_name='verificationtokens',
            name='access_veri_token_h_80b19c_idx',
        ),
        migrations.AddField(
            model_name='organizationtokens',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_tokens', to='organization.organizations'),
        ),
        migrations.AddField(
            model_name='organizationtokens',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_tokens', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='verificationtokens',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='verificationtokens',
            name='user',
        ),
        migrations.AddIndex(
            model_name='organizationtokens',
            index=models.Index(fields=['token_hash'], name='access_orga_token_h_842df5_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtokens',
            index=models.Index(fields=['user'], name='access_orga_user_id_2a813f_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtokens',
            index=models.Index(fields=['token_type'], name='access_orga_token_t_d0d116_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtokens',
            index=models.Index(fields=['expires_at'], name='access_orga_expires_28dda7_idx'),
        ),
        migrations.AddIndex(
            model_name='organizationtokens',
            index=models.Index(fields=['token_hash', 'token_type', 'user'], name='access_orga_token_h_3f9fe1_idx'),
        ),
        migrations.DeleteModel(
            name='VerificationTokens',
        ),
    ]
