# Generated by Django 6.0.5 on 2026-07-23 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        ('organization', '0002_rename_timezone_organizationsettings_time_zone_and_more'),
        ('terminals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFIDEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(db_index=True, help_text='Unique MQTT message ID — used for idempotency deduplication', max_length=100, unique=True)),
                ('raw_tag_id', models.CharField(db_index=True, help_text='Raw EPC tag ID read by the RFID reader', max_length=100)),
                ('direction', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit')], max_length=10)),
                ('signal_strength', models.FloatField(blank=True, help_text='RSSI signal strength in dBm — used to filter weak reads', null=True)),
                ('is_recognized', models.BooleanField(default=True, help_text='False if tag was not found in fleet registry')),
                ('status_triggered', models.CharField(blank=True, help_text='Truck status that was set as a result of this event', max_length=30, null=True)),
                ('event_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp of when the tag was detected at the reader')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_events', to='terminals.gates')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_events', to='organization.organizations')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_events', to='terminals.terminals')),
                ('truck', models.ForeignKey(blank=True, help_text='Resolved truck — null if tag was unrecognized', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_events', to='fleet.truck')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='RFIDAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_tag_id', models.CharField(db_index=True, max_length=100)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution_note', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='terminals.gates')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfid_alerts', to='organization.organizations')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_rfid_alerts', to=settings.AUTH_USER_MODEL)),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='terminals.terminals')),
                ('rfid_event', models.OneToOneField(help_text='The RFID event that triggered this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alert', to='rfid_events.rfidevent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFIDReaderStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reader_id', models.CharField(db_index=True, help_text='Unique reader identifier matching MQTT client ID', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('online', 'Online'), ('degraded', 'Degraded'), ('offline', 'Offline')], default='online', max_length=20)),
                ('firmware_version', models.CharField(blank=True, max_length=20, null=True)),
                ('uptime_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_heartbeat', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gate', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reader_status', to='terminals.gates')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reader_statuses', to='organization.organizations')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reader_statuses', to='terminals.terminals')),
            ],
            options={
                'ordering': ['reader_id'],
            },
        ),
        migrations.AddIndex(
            model_name='rfidevent',
            index=models.Index(fields=['raw_tag_id'], name='rfid_events_raw_tag_d1b0a7_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidevent',
            index=models.Index(fields=['event_time'], name='rfid_events_event_t_5dd1b2_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidevent',
            index=models.Index(fields=['is_recognized'], name='rfid_events_is_reco_38edb2_idx'),
        ),
        migrations.AddIndex(
            model_name='rfidevent',
            index=models.Index(fields=['organization', 'event_time'], name='rfid_events_organiz_b2647b_idx'),
        ),
    ]
