# Generated by Django 6.0.5 on 2026-06-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_timezone_organizationsettings_time_zone_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('org_admin', 'Org Admin'), ('management', 'Management'), ('logistics_officer', 'Logistics Officer'), ('tracking_officer', 'Tracking Officer'), ('workshop', 'Workshop'), ('sales_analyst', 'Sales / Analyst'), ('customer', 'Customer'), ('driver', 'Driver')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organization.organizations')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.role'),
        ),
        migrations.DeleteModel(
            name='UserRole',
        ),
    ]
