# Generated by Django 6.0.5 on 2026-07-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_alter_user_role_delete_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('org_admin', 'Org Admin'), ('management', 'Management'), ('logistics_officer', 'Logistics Officer'), ('tracking_officer', 'Tracking Officer'), ('workshop', 'Workshop'), ('sales', 'Sales / Marketer'), ('customer', 'Customer'), ('driver', 'Driver')], max_length=50),
        ),
    ]
