# Generated by Django 6.0.5 on 2026-07-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_deleted_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='role',
            name='organization',
        ),
    ]
