# Generated by Django 6.0.5 on 2026-08-02 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_timezone_organizationsettings_time_zone_and_more'),
        ('users', '0008_alter_role_unique_together_remove_role_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organizations'),
        ),
    ]
