# Generated by Django 6.0.5 on 2026-07-23 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0002_initial'),
        ('organization', '0002_rename_timezone_organizationsettings_time_zone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETAModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('training', 'Training'), ('active', 'Active'), ('retired', 'Retired'), ('failed', 'Failed')], db_index=True, default='training', max_length=20)),
                ('records_used', models.PositiveIntegerField()),
                ('mae_minutes', models.FloatField(blank=True, null=True)),
                ('rmse_minutes', models.FloatField(blank=True, null=True)),
                ('mape_percentage', models.FloatField(blank=True, null=True)),
                ('model_file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('trained_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_model_versions', to='organization.organizations')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('organization', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ETATripRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('base_eta_minutes', models.FloatField(blank=True, help_text='Stage 1 routing API estimate in minutes', null=True)),
                ('hour_of_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('driver_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('origin_terminal_id', models.IntegerField(blank=True, null=True)),
                ('product_name', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('actual_duration_minutes', models.FloatField(help_text='Actual trip duration — the target variable for model training')),
                ('departed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eta_record', to='dispatch.dispatch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eta_records', to='organization.organizations')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='eta_etatrip_organiz_1240d9_idx'), models.Index(fields=['driver_id'], name='eta_etatrip_driver__70d70b_idx'), models.Index(fields=['origin_terminal_id'], name='eta_etatrip_origin__47e2d3_idx')],
            },
        ),
    ]
