# Generated by Django 6.0.5 on 2026-06-16 13:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organization", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationsettings",
            old_name="timezone",
            new_name="time_zone",
        ),
        migrations.AlterField(
            model_name="organizations",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="organizationsettings",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
