# Generated by Django 6.0.5 on 2026-08-10 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_rename_timezone_organizationsettings_time_zone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('org_admin', 'Org Admin'), ('management', 'Management'), ('logistics_officer', 'Logistics Officer'), ('tracking_officer', 'Tracking Officer'), ('workshop', 'Workshop'), ('sales', 'Sales / Marketer'), ('customer', 'Customer'), ('driver', 'Driver')], default='logistics_officer', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organization.organizations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'organization_members',
                'indexes': [models.Index(fields=['organization', 'user'], name='organizatio_organiz_324912_idx'), models.Index(fields=['role'], name='organizatio_role_96c282_idx')],
                'unique_together': {('organization', 'user')},
            },
        ),
    ]
