# Generated by Django 6.0.5 on 2026-07-07 15:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('organization', '0002_rename_timezone_organizationsettings_time_zone_and_more'),
        ('terminals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confirmed_by_name', models.CharField(help_text='Name of customer contact who confirmed delivery', max_length=255)),
                ('confirmed_by_phone', models.CharField(max_length=20)),
                ('waybridge_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Quantity recorded at customer waybridge in product unit', max_digits=10, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=3, help_text='Dispatched quantity minus waybridge weight — computed on save', max_digits=10, null=True)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_flagged', models.BooleanField(default=False, help_text='True if variance exceeds the configured threshold')),
                ('confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Delivery Confirmation',
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waybill_number', models.CharField(db_index=True, max_length=100, unique=True)),
                ('sales_order_no', models.CharField(blank=True, help_text='ERP sales order reference number', max_length=100, null=True, unique=True)),
                ('quantity', models.DecimalField(decimal_places=3, help_text="Quantity dispatched in the product's unit of measurement", max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('loading', 'Loading'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Customer'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('expected_departure', models.DateTimeField(blank=True, null=True)),
                ('actual_departure', models.DateTimeField(blank=True, help_text='Set automatically when RFID gate exit event is processed', null=True)),
                ('eta', models.DateTimeField(blank=True, help_text='Estimated time of arrival — computed by ETA prediction module', null=True)),
                ('arrival_token', models.CharField(blank=True, help_text='6-digit OTP sent to customer on driver arrival — null until status is ARRIVED', max_length=6, null=True)),
                ('arrival_token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('arrival_token_attempts', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_dispatches', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispatches', to='customers.customer')),
                ('delivery_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='customers.deliveryaddress')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispatches', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='organization.organizations')),
                ('origin_terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='terminals.terminals')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchStatusLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('previous_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('loading', 'Loading'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Customer'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20, null=True)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('loading', 'Loading'), ('dispatched', 'Dispatched'), ('in_transit', 'In Transit'), ('arrived', 'Arrived at Customer'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('trigger_source', models.CharField(choices=[('rfid', 'RFID Gate Event'), ('manual', 'Manual Override'), ('driver', 'Driver Action'), ('customer', 'Customer Confirmation'), ('system', 'System')], default='system', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripMetadata',
            fields=[
                ('dispatch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='trip_metadata', serialize=False, to='dispatch.dispatch')),
                ('scale_in_time', models.DateTimeField(blank=True, null=True)),
                ('scale_out_time', models.DateTimeField(blank=True, null=True)),
                ('tare_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Empty truck weight in tonnes', max_digits=10, null=True)),
                ('gross_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Loaded truck weight in tonnes', max_digits=10, null=True)),
                ('net_weight', models.DecimalField(blank=True, decimal_places=3, help_text='Product weight — gross minus tare', max_digits=10, null=True)),
                ('rob', models.CharField(blank=True, help_text='Remaining on board — product left in truck from previous trip', max_length=100, null=True)),
                ('seal_numbers', models.CharField(blank=True, help_text='Comma-separated seal numbers applied at loading', max_length=255, null=True)),
                ('loading_temp', models.DecimalField(blank=True, decimal_places=2, help_text='Product temperature at loading in degrees Celsius', max_digits=6, null=True)),
                ('fuel_intank', models.DecimalField(blank=True, decimal_places=2, help_text='Fuel level at departure in litres', max_digits=8, null=True)),
                ('odometer_departure', models.PositiveIntegerField(blank=True, help_text='Odometer reading at departure in km', null=True)),
                ('odometer_arrival', models.PositiveIntegerField(blank=True, help_text='Odometer reading at arrival in km — used for mileage fraud detection', null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Trip Metadata',
                'verbose_name_plural': 'Trip Metadata',
            },
        ),
    ]
