# Generated by Django 6.0.5 on 2026-07-07 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dispatch', '0001_initial'),
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispatches', to='fleet.product'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatches', to='fleet.route'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='dispatches', to='fleet.truck'),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='dispatch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmation', to='dispatch.dispatch'),
        ),
        migrations.AddField(
            model_name='dispatchstatuslog',
            name='dispatch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='dispatch.dispatch'),
        ),
        migrations.AddField(
            model_name='dispatchstatuslog',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_status_changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
