# Generated by Django 6.0.5 on 2026-08-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='actual_arrival',
            field=models.DateTimeField(blank=True, help_text='Actual time the truck arrived at the customer and delivery was completed', null=True),
        ),
    ]
